[package]
name = "forager"
version = "0.1.0"
authors = ["mzyzc <mzyzc@czyz.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.15" }
gio = { version = "0.15" }
curl = "0.4"
roxmltree = "0.13"
